### ISSUE TITLE
message type

### ISSUE THREAD

**Issue by diaozatian** [mariobadr/synfull-isca#1]
As you writted in the file , there are four message types : read , write , ccr , dcr.   what does the ccr and dcr mean?

**Comment by diaozatian** [comment]
what is the function of MyRand.cpp and PacketQueue.cpp ?

**Comment by mariobadr** [comment]
CCR and DCR refer to clean and dirty cache replacements, respectively. Because the model abstracts away the core and its private caches, there could be cache replacement messages created due to evictions. These message types model that traffic.

**Comment by mariobadr** [comment]
The PacketQueue allows you to send a message at a certain time. You can use DeQueue at different timestamps to retrieve all the packets that have been EnQueued for that timestamp.

**Comment by mariobadr** [comment]
MyRand is just a small wrapper around the random distributions available from C++11 onwards. It represents different types of distributions (e.g., uniform, bernoulli, etc) that I was experimenting with.
